# Configuration

site_name: Machine Learning datasets
repo_url: https://github.com/bpiwowar/datamaestro_ml

# Theme
theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Main pages
nav:
  - Home: index.md
    

# Automatic page generation for datasets
plugins:
  - datamaestro: 
        repository: ml
  - search
  