version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: PyPI
          filters:
              tags:
                only: /.*/
      - test-python-install:
          version: "3.6"
          requires:
            - build
      - test-python-install:
          version: "3.7"
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - run: 
          name: Upload
          command: |
            if [ "$CIRCLE_TAG" ]; then
              echo "Uploading using twine"
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
              . venv/bin/activate
              python setup.py verify
              make package
              twine upload dist/*
            fi

  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
